# Generated by Django 2.2 on 2019-04-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20190415_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
