# Generated by Django 2.2 on 2019-04-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='order',
        ),
    ]
